<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.horadrim</groupId>
  <artifactId>Horadric-Staff-Spark-Jobs</artifactId>
  <packaging>pom</packaging>
  <version>${project.version}</version>
  <name>horadrim-spark-jobs</name>

  <parent>
    <groupId>com.horadrim</groupId>
    <artifactId>Horadric-Staff</artifactId>
  </parent>

  <modules>
    <module>word-count</module>
  </modules>
</project>
